ALTER TABLE `marketplace`.`discount` 
CHANGE COLUMN `bonus` `bonus` DECIMAL(5,2) NULL DEFAULT NULL ,
CHANGE COLUMN `start` `start` TIMESTAMP NULL DEFAULT NULL ,
CHANGE COLUMN `finish` `finish` TIMESTAMP NULL DEFAULT NULL ;
