INSERT INTO `db1`.`group_` (`group_name`, `teacher_id`) VALUES ('11-901', '1');
INSERT INTO `db1`.`group_` (`group_name`, `teacher_id`) VALUES ('11-902', '2');
INSERT INTO `db1`.`group_` (`group_name`, `teacher_id`) VALUES ('11-903', '3');
INSERT INTO `db1`.`group_` (`group_name`, `teacher_id`) VALUES ('11-904', '1');
INSERT INTO `db1`.`group_` (`group_name`, `teacher_id`) VALUES ('11-905', '1');
INSERT INTO `db1`.`group_` (`group_name`, `teacher_id`) VALUES ('11-906', '2');
INSERT INTO `db1`.`group_` (`group_name`, `teacher_id`) VALUES ('11-907', '3');
INSERT INTO `db1`.`user` (`username`, `email`, `password`, `create_time`) VALUES ('Kate', 'njekkv', 'ewmdkl', '2020-01-01 10:10:10');
INSERT INTO `db1`.`user` (`username`, `email`, `password`, `create_time`) VALUES ('Michael', 'wqefrg', 'qwefr', '2020-01-02 10:10:10');
INSERT INTO `db1`.`user` (`username`, `email`, `password`, `create_time`) VALUES ('Alia', 'efwrt', 'dewfgtrhygr', '2020-01-03 10:10:10');
INSERT INTO `db1`.`user` (`username`, `email`, `password`, `create_time`) VALUES ('Bill', 'brgfds', 'gerf', '2020-01-04 10:10:10');
INSERT INTO `db1`.`user` (`username`, `email`, `password`, `create_time`) VALUES ('Bob', 'gtrefdw', 'gerfwd', '2020-01-05 10:10:10');
INSERT INTO `db1`.`user` (`username`, `email`, `password`, `create_time`) VALUES ('Penelope', 'wefrgt', 'fgtrfd', '2020-01-01 10:15:10');
INSERT INTO `db1`.`mark` (`student_id`, `mark`) VALUES ('1', '5');
INSERT INTO `db1`.`mark` (`student_id`, `mark`) VALUES ('2', '3');
INSERT INTO `db1`.`mark` (`student_id`, `mark`) VALUES ('2', '3');
INSERT INTO `db1`.`mark` (`student_id`, `mark`) VALUES ('1', '3');
INSERT INTO `db1`.`mark` (`student_id`, `mark`) VALUES ('3', '4');
INSERT INTO `db1`.`mark` (`student_id`, `mark`) VALUES ('3', '2');
INSERT INTO `db1`.`student` (`user_id`, `group_id`) VALUES ('1', '1');
INSERT INTO `db1`.`student` (`user_id`, `group_id`) VALUES ('2', '3');
INSERT INTO `db1`.`student` (`user_id`, `group_id`) VALUES ('3', '6');
INSERT INTO `db1`.`teacher` (`user_id`) VALUES ('4');
INSERT INTO `db1`.`teacher` (`user_id`) VALUES ('5');
INSERT INTO `db1`.`teacher` (`user_id`) VALUES ('6');